
package team9.ws.faktura;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FakturaService", targetNamespace = "http://team9/ws/faktura", wsdlLocation = "file:/home/gajop/bsep/xws-bsep-project/scheme/faktura.wsdl")
public class FakturaService
    extends Service
{

    private final static URL FAKTURASERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(team9.ws.faktura.FakturaService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = team9.ws.faktura.FakturaService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/gajop/bsep/xws-bsep-project/scheme/faktura.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/gajop/bsep/xws-bsep-project/scheme/faktura.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        FAKTURASERVICE_WSDL_LOCATION = url;
    }

    public FakturaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FakturaService() {
        super(FAKTURASERVICE_WSDL_LOCATION, new QName("http://team9/ws/faktura", "FakturaService"));
    }

    /**
     * 
     * @return
     *     returns Faktura
     */
    @WebEndpoint(name = "FakturaPort")
    public Faktura getFakturaPort() {
        return super.getPort(new QName("http://team9/ws/faktura", "FakturaPort"), Faktura.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Faktura
     */
    @WebEndpoint(name = "FakturaPort")
    public Faktura getFakturaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://team9/ws/faktura", "FakturaPort"), Faktura.class, features);
    }

}
