
package team9.ws.nalog_za_placanje;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Nalog_za_placanje", targetNamespace = "http://team9/ws/nalog_za_placanje")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NalogZaPlacanje {


    /**
     * 
     * @param stavka
     * @param zaglavlje
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "nalog_za_placanje")
    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "nalog_za_placanje", targetNamespace = "http://team9/ws/nalog_za_placanje", className = "team9.ws.nalog_za_placanje.NalogZaPlacanje_Type")
    @ResponseWrapper(localName = "nalog_za_placanjeResponse", targetNamespace = "http://team9/ws/nalog_za_placanje", className = "team9.ws.nalog_za_placanje.NalogZaPlacanjeResponse")
    public boolean nalogZaPlacanje(
        @WebParam(name = "zaglavlje", targetNamespace = "http://team9/ws/nalog_za_placanje")
        team9.ws.nalog_za_placanje.NalogZaPlacanje_Type.Zaglavlje zaglavlje,
        @WebParam(name = "stavka", targetNamespace = "http://team9/ws/nalog_za_placanje")
        List<team9.ws.nalog_za_placanje.NalogZaPlacanje_Type.Stavka> stavka);

}
