
package team9.ws.presek;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Presek", targetNamespace = "http://team9/ws/presek")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Presek {


    /**
     * 
     * @param stavka
     * @param zaglavlje
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "success", targetNamespace = "")
    @RequestWrapper(localName = "presek", targetNamespace = "http://team9/ws/presek", className = "team9.ws.presek.Presek_Type")
    @ResponseWrapper(localName = "presekResponse", targetNamespace = "http://team9/ws/presek", className = "team9.ws.presek.PresekResponse")
    public boolean presek(
        @WebParam(name = "zaglavlje", targetNamespace = "http://team9/ws/presek")
        team9.ws.presek.Presek_Type.Zaglavlje zaglavlje,
        @WebParam(name = "stavka", targetNamespace = "http://team9/ws/presek")
        List<team9.ws.presek.Presek_Type.Stavka> stavka);

}
