
package team9.ws.rtgs_nalog;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RTGS_nalogService", targetNamespace = "http://team9/ws/RTGS_nalog", wsdlLocation = "file:/home/gajop/bsep/xws-bsep-project/scheme/RTGS_nalog.wsdl")
public class RTGSNalogService
    extends Service
{

    private final static URL RTGSNALOGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(team9.ws.rtgs_nalog.RTGSNalogService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = team9.ws.rtgs_nalog.RTGSNalogService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/gajop/bsep/xws-bsep-project/scheme/RTGS_nalog.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/gajop/bsep/xws-bsep-project/scheme/RTGS_nalog.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RTGSNALOGSERVICE_WSDL_LOCATION = url;
    }

    public RTGSNalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RTGSNalogService() {
        super(RTGSNALOGSERVICE_WSDL_LOCATION, new QName("http://team9/ws/RTGS_nalog", "RTGS_nalogService"));
    }

    /**
     * 
     * @return
     *     returns RTGSNalog
     */
    @WebEndpoint(name = "RTGS_nalogPort")
    public RTGSNalog getRTGSNalogPort() {
        return super.getPort(new QName("http://team9/ws/RTGS_nalog", "RTGS_nalogPort"), RTGSNalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RTGSNalog
     */
    @WebEndpoint(name = "RTGS_nalogPort")
    public RTGSNalog getRTGSNalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://team9/ws/RTGS_nalog", "RTGS_nalogPort"), RTGSNalog.class, features);
    }

}
