
package team9.ws.zahtev_za_izvod;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Zahtev_za_izvodService", targetNamespace = "http://team9/ws/zahtev_za_izvod", wsdlLocation = "file:/home/gajop/bsep/xws-bsep-project/scheme/zahtev_za_izvod.wsdl")
public class ZahtevZaIzvodService
    extends Service
{

    private final static URL ZAHTEVZAIZVODSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(team9.ws.zahtev_za_izvod.ZahtevZaIzvodService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = team9.ws.zahtev_za_izvod.ZahtevZaIzvodService.class.getResource(".");
            url = new URL(baseUrl, "file:/home/gajop/bsep/xws-bsep-project/scheme/zahtev_za_izvod.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/home/gajop/bsep/xws-bsep-project/scheme/zahtev_za_izvod.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ZAHTEVZAIZVODSERVICE_WSDL_LOCATION = url;
    }

    public ZahtevZaIzvodService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZahtevZaIzvodService() {
        super(ZAHTEVZAIZVODSERVICE_WSDL_LOCATION, new QName("http://team9/ws/zahtev_za_izvod", "Zahtev_za_izvodService"));
    }

    /**
     * 
     * @return
     *     returns ZahtevZaIzvod
     */
    @WebEndpoint(name = "Zahtev_za_izvodPort")
    public ZahtevZaIzvod getZahtevZaIzvodPort() {
        return super.getPort(new QName("http://team9/ws/zahtev_za_izvod", "Zahtev_za_izvodPort"), ZahtevZaIzvod.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZahtevZaIzvod
     */
    @WebEndpoint(name = "Zahtev_za_izvodPort")
    public ZahtevZaIzvod getZahtevZaIzvodPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://team9/ws/zahtev_za_izvod", "Zahtev_za_izvodPort"), ZahtevZaIzvod.class, features);
    }

}
